name: worker_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  firebase_core: '^0.5.3'
  firebase_analytics: '^6.0.0'
  firebase_auth: '^0.18.0+1'
  cloud_firestore: '^0.14.0+2'
  syncfusion_flutter_calendar: ^18.3.47
  flutter_local_notifications: 1.4.4+4
  photo_view: ^0.10.2
  firebase_storage: ^4.0.0
  firebase_database: ^4.4.0
  cached_network_image: ^2.3.1
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.10
  image_picker: ^0.6.7+7
  # google_sign_in:
  # apple_sign_in:
  get:
  get_storage: ^1.3.1

  # flutter_platform_widgets:
  flutter_sheet_localization: ^2.0.0
  simple_gravatar:
  percent_indicator: "^2.1.5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^2.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
    - images/img_not_available.jpeg
    - images/mimi1.gif
    - images/mimi2.gif
    - images/mimi3.gif
    - images/mimi4.gif
    - images/mimi5.gif
    - images/mimi6.gif
    - images/mimi7.gif
    - images/mimi8.gif
    - images/mimi9.gif
